import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Connect from '@mono.co/connect.js';
import Header from '../components/Header';

import Car from '../assets/car.jpg';
import House from '../assets/house.jpg';
import Shop from '../assets/shop.jpg';

const Home: NextPage = () => {
  const monoConnect = React.useMemo(() => {
    if (typeof window !== 'undefined') {
      const monoInstance = new Connect({
        key: process.env.NEXT_PUBLIC_MONO_PUB,
        onSuccess: (data: any) => {
          console.log('successData', data);
        },
        onLoad: () => console.log('widget loaded successfully'),
        onClose: () => console.log('widget has been closed'),
        onEvent: (eventName: any, data: any) => {
          console.log('eventName', eventName);
          console.log('eventData', data);
        },
      });

      monoInstance.setup();

      return monoInstance;
    }
  }, []);

  return (
    <div>
      <Head>
        <title>Quadro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="min-h-screen">
        <div className="flex flex-col items-center mt-20 gap-20">
          <div className="max-w-xl mx-auto">
            <h1 className="font-bold text-6xl text-center">
              Afford your dreams with our new credit ratings.
            </h1>
          </div>

          <div className="font-bold flex flex-col items-center gap-4 text-2xl">
            <p>Dreamers. Futurists. Businesses.</p>
            <button className="bg-primary-gray rounded-2xl px-6 py-1">
              Get started
            </button>
          </div>
        </div>

        <div className="flex justify-center h-[700px] w-full mt-20">
          <div className="flex justify-center relative w-2/3 gap-10 max-w-[790px]">
            <div className="w-1/3 h-[550px] relative self-end">
              <Image
                src={Car}
                alt="photo of car"
                layout="fill"
                objectFit={'cover'}
              />
            </div>
            <div className="w-1/3 h-[550px] relative">
              <Image
                src={House}
                alt="photo of house"
                layout="fill"
                objectFit="cover"
              />
            </div>
            <div className="w-1/3 h-[550px] relative self-end">
              <Image
                src={Shop}
                alt="photo of shop"
                layout="fill"
                objectFit="cover"
              />
            </div>
          </div>
        </div>
        <div className="flex items-center justify-center flex-wrap max-w-3xl">
          <button
            onClick={() => monoConnect.open()}
            className="text-left p-6 border border-blue-400 rounded-xl max-w-xs m-8"
          >
            <h2>Connect</h2>
            <p>Use Connect.js framework to connect to Mono</p>
          </button>
        </div>
      </main>
    </div>
  );
};

export default Home;
