/* eslint-disable @next/next/no-img-element */
import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

import Header from '../components/Header';
import Rating from '../components/Rating';
import Illustration1 from '../assets/ill_1.png';
import Illustration2 from '../assets/ill_2.png';
import HowItWorks from '../components/HowItWorks';
import scrollTo from '../utils/scrollTo';

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Quadro</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Header />
    <main>
      <div className="flex flex-col items-center justify-center h-screen gap-20 px-4 bg-primary-gray">
        <img
          src={Illustration1.src}
          alt="Promotional ilustration"
          className="absolute right-5 bottom-0 hidden md:block md:h-[500px] aspect-1 blur-md"
        />
        <div className="z-10 max-w-4xl mx-auto space-y-6 text-center animate-fade">
          <h1 className="text-6xl font-bold uppercase">
            Track your credit while you build
          </h1>

          <p>
            We generate a credit score based on your financial data to inform
            lending and your borrowing.
          </p>
        </div>

        <div className="z-10 flex flex-col items-center gap-4 text-2xl font-medium text-center animate-fade">
          <p>Dreamers. Futurists. Businesses.</p>
        </div>

        <button
          type="button"
          onClick={() => scrollTo('how')}
          className="z-10 p-3 px-8 text-white rounded-md bg-primary-green animate-fade"
        >
          Get started
        </button>
      </div>
      <div className="relative">
        <img
          src={Illustration2.src}
          alt="Promotional ilustration"
          className="absolute left-5 bottom-0 hidden md:block h-0 md:h-[500px] aspect-1 blur-md"
        />
        <div className="relative bg-[#f8ba37] h-screen m-auto flex flex-col justify-center p-6">
          <HowItWorks />
        </div>
        <div className="relative max-w-[1440px] h-screen m-auto flex flex-col justify-center p-6">
          <Rating />
        </div>
      </div>
    </main>
  </div>
);

export default Home;
