import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';

import Rating from '../components/Rating';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Quadro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <div className="flex flex-col items-center justify-center -mt-20 gap-20 h-screen">
          <div className="max-w-4xl mx-auto text-center space-y-6">
            <h1 className="font-bold text-6xl uppercase">
              Track your credit while you build
            </h1>

            <p>
              We generate a credit score based on your financial data to inform
              lending and your borrowing.
            </p>
          </div>

          <div className="font-medium flex flex-col items-center gap-4 text-2xl">
            <p>Dreamers. Futurists. Businesses.</p>
          </div>

          <a
            href="#rate"
            className="px-8 bg-primary-green text-white p-3 rounded-md"
          >
            Get started
          </a>
        </div>
        <div className="max-w-[1440px] h-screen m-auto flex flex-col justify-center p-6">
          <Rating />
        </div>
      </main>
    </div>
  );
};

export default Home;
